# Generated by Django 2.1.15 on 2020-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_document_post_tbadjcell_tbatuc2i_tbatudata_tbatuhandover_tbc2i_tbcell_tbhandover_tbmrodata_tboptcell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=''),
        ),
    ]
