# Generated by Django 2.1.15 on 2020-08-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200801_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
