# Generated by Django 2.1.15 on 2020-08-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_tbkpi_tbprb'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbkpi',
            table='tbKPI',
        ),
        migrations.AlterModelTable(
            name='tbprb',
            table='tbPRB',
        ),
    ]
